language: java
jdk:
  - openjdk8
dist: trusty

cache:
  directories:
    - $HOME/.gradle/

# We depend on a wildfly deploment for some of the production
# jar files. Download it and install just above our repo
before_script:
  - wget http://download.jboss.org/wildfly/10.1.0.Final/wildfly-10.1.0.Final.tar.gz -O /tmp/wildfly-10.1.0.Final.tar.gz
  - pushd ..
  - tar -xvf /tmp/wildfly-10.1.0.Final.tar.gz
  - popd

install: true

# The build step here also builds our Javadocs.
script:
  - cd psm-app
  - ./gradlew --no-daemon --console=plain clean build cms-web:apiDocs
  - cd ../

# Push the new Javadocs to our GitHub Pages site.
after_success:
  - ./scripts/push-javadoc-to-gh-pages.sh

# Build the Continuous Deployment private key
before_deploy:
  - echo $CD_KEY > deploy_rsa
  - sed -i -e 's/ /\n/g' deploy_rsa
  - head -n -4 deploy_rsa > tmp
  - tail -n +5 tmp > deploy_rsa
  - rm tmp
  - sed -i '1s/^/-----BEGIN RSA PRIVATE KEY-----\n/' deploy_rsa
  - sed -i -e "\$a-----END RSA PRIVATE KEY-----" deploy_rsa
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy_rsa
  - ssh-add deploy_rsa
  - rm deploy_rsa

# Continuous Deployment
deploy:
  provider: script
  skip_cleanup: true
  script: sh scripts/deploy-ci.sh
  on:
    branch: master
