language: java
jdk:
  - openjdk8
dist: trusty

cache:
  directories:
    - $HOME/.gradle/

# We depend on a wildfly deploment for some of the production
# jar files. Download it and install just above our repo
before_script:
  - wget http://download.jboss.org/wildfly/10.1.0.Final/wildfly-10.1.0.Final.tar.gz -O /tmp/wildfly-10.1.0.Final.tar.gz
  - pushd ..
  - tar -xvf /tmp/wildfly-10.1.0.Final.tar.gz
  - popd

install: true

# The build step here also builds our Javadocs.
script:
  - cd psm-app
  - ./gradlew --no-daemon --console=plain clean build cms-web:apiDocs
  - cd ../

# Push the new Javadocs to our GitHub Pages site.
after_success:
  - ./scripts/push-javadoc-to-gh-pages.sh

# Continuous Deployment
env:
  global:
  - secure: "JE68v/aK+J2bnu49IdZ7/o+1OTcOnDqcK3N4OyKBDeP2DkI5BAUKk4Q4/0LVzucVFI5UGuKJ0907grS3hGF7wtEv8DMhAIlrZILO0rJLBkawevBzN9QtwoRvLlY0nGEiVHlugNXq8CLGL0mo8NjU6rk8fscq871FgNDIfvUk4stwJOZx2Hv2BKBR13smryOP3CWnXRbU7bqbPqI1Zk8+HH+f6qpzCLAx7gP8PqwAUpr6EuVRQKopnlvjeKpqtUWaOyyGxKVJY4ceRTesk7bojzPrhI67phRweEVZgsX8f8IfR2HoFEFfVAsG1qMWxWazDhwKU8ElVocRJn+iM/Ap6W6yeviSPS5lzgixNijxz4b9T8mSdS/PGIBpM8GXIdwxABhHYQ281kTGWH3zndyc7GC/OIqdNztPNcpV2ISe2Xoifpw80BhmdjcMeWbWt0k9Sb0ll8TRPA4VA6RX+o9wCESGOafjK2ZiZU/xIaLpuO8CFaJw4YrKdkhdQQTj9T/AIQo9S6jQBwGAOZbYnY3JU9k/BLbrgSZtbixEGBZlCcq0m+hnf/iWluwsB0ZHYBuyVYC6noY2j3RywfXD3vUa3cSbr67X4lTaGh5OrzdznJzrpxKy3rsjc7k4h9/+DIlw4q3vKctOhwTe6Cy+99wRzeWY5qEehmzaNKalj5P7PpA="
  - secure: "uKKODxo7VBfN906T6IbqTCV29adsa8tl5YBxjOtf41c3yOkHlTtAwowgEfSsYnWI2qmqnQNbxhmxWxj5e/c4HTErxXykqn9v9zInXZhkro1zPHQbZkz90M7c/qnkYDqWY6l6G1gMuJxPcAvH8Kc3ltSlVmFUf7OC0oG+3yIRb8jTZUjTeORAjD7yMmqEIxBnn1x7pEV+eNeP75u5Rfp8kbuSRCE01U2o8F9F8qc2b65e0HhvsA6RPDf3G7CEkK7vnRTy3MuoOPzC1+8rMeKA2aFcUYZeLpS5FXoA64gVxH7O2M4JBetjGEKG/tsMRW6XwbV9eg3T+ToEGI5dnZaoFb6Mvd7AJoyscNRDxNkIdaNYRSeAZwGMtO0NqoPJIGSNf9YLE/NYjM5m7T2pJaJACeDWMhD7CdX309DDqXd3EbXOgbR92Iui27MWu7RQzL8vpJG48VDm4evLY9dG8XcGGG5oVFjO7UZcFm6/tS6zQlqAELd0oTMGa+ajCOQQNvJHDKrGu0ExOVQX0hppv/lsU/RPVfZGMFiZKf1mNMUOeb3zTNQJE10IUi4GZcRs+NZr5LKJ9ks7SvwHpB+RqgUz642j+kpiYzmEMFBUJLa7us/wu57CSQfXMcooPbW/hxLxopES2KURdYwJdX0cDteWigbtJdmmM1rVMaTopk3c2ME="

before_deploy:
  - openssl aes-256-cbc -K $encrypted_f64cd7b1869a_key -iv $encrypted_f64cd7b1869a_iv
    -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy_rsa
  - ssh-add deploy_rsa
  - rm deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: sh scripts/deploy-ci.sh
  on:
    branch: 222-continuous-deployment
